version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building Site on `date`
      - pwd
      - npm run build
      - echo copy to s3
      - aws s3 sync dist s3://stefantopia-10-17-2023
artifacts:
  files:
    - "dist/*"
    - "dist/**/*"