version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npx cypress run
    finally:
      - aws s3 sync cypress/screenshots s3://stefantopia-9-25-2023/cypress/report/screenshots
      - aws s3 sync cypress/videos s3://stefantopia-9-25-2023/cypress/report/videos
      
artifacts:
  files:
    - "**/*"