version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
      - echo copy to s3
      - aws s3 sync dist s3://stefantopia-7-24-2023
artifacts:
  files:
    - "dist/*"
    - "dist/**/*"