version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building Test on `date`
      - pwd
      - npx cypress run
    finally:
      - aws s3 rm s3://stefantopia-9-25-2023/cypress --recursive  
      - cd cypress
      - python generate_links.py
      - aws s3 cp cypress s3://stefantopia-9-25-2023/cypress --recursive  
      
artifacts:
  files:
    - "**/*"