version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - node_modules/.bin/cypress run
artifacts:
  files:
    - "cypress/*"
    - "cypress/**/*"